

   
services:
 ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    build:
      context: C:/Users/MICRO/Downloads/DeveloperStore/template/backend
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on: 
        - localhost
    environment:
        - ASPNETCORE_ENVIROMENT=Development
        - ASPNETCORE_URLS=http://+:5000
        - DOTNET_USE_POLLING_FILE_WATCHER=1
    restart: on-failure
    networks:
    - developerevaluationnetwork

 localhost:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserverdb_compose
    environment:
        SA_PASSWORD: "P@ssw0rd2103"
        ACCEPT_EULA: "Y"
    ports:
    - "1450:1433"
    volumes:
    - sqlvolume:/var/opt/mssql
    networks:
    - developerevaluationnetwork

networks:
  developerevaluationnetwork:

volumes:
  sqlvolume:
